### ISSUE TITLE
Datago Benchmark Results

### ISSUE THREAD

**Issue by conceptofmind** [Photoroom/datago#32]
Hi @blefaudeux ,

I am currently testing the benchmark script on a set of 2000 images.

The Datago dataloader gets 64 FPS and the Torch dataloader gets 135 FPS.

Here are the results from the benchmark script:
```
Running benchmark for /nvme_data/images/ - 2000 samples
datago.GeneratorFileSystemConfig
Creating a FileSystem-backed dataloader
File system root directory /nvme_data/images/
Supported image extensions [.jpg .jpeg .png .JPEG .JPG .PNG]
Rank and World Size 0 1
Cropping and resizing images
Base image size | downsampling ratio | min | max: 512 16 0.5 2
Datago FPS 64.21
Stopping the dataroom client
Metadata fetch goroutine wrapping up
No more items to serve, wrapping up
Dataroom client stopped
Benchmarking torch dataloader
Torch FPS 135.90
```
Datago is installed through pypi: https://pypi.org/project/datago/

Python version is 3.11.10.

OS is Ubuntu 22.04.

Should these results be expected? Or would the difference be seen on a much larger set of data?

I appreciate all of your help.

Thank you,

Enrico

**Comment by blefaudeux** [comment]
that's not a lot of FPS :) glad to see that it works for you to begin with ! hard to say for sure without seeing the data, but couple of points
- you can change the "concurrency" setting in Datago, maybe you're not quite at the optimal setting
- Datago does a high quality resize, it's activated by default in the benchmark. Torch does a low quality resize (in that benchmark), the default from [here](https://pytorch.org/vision/stable/generated/torchvision.transforms.Resize.html?highlight=resize#torchvision.transforms.Resize) is being used which is low quality. Higher quality is possible for Pytorch, it will slow things down 
- I would need to check that, but you need [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo) installed on your machine to get the best speed, else datago will fall back to libjpeg which is much slower. On ubuntu it's as simple as `sudo apt install libjpeg-turbo8`

**Comment by conceptofmind** [comment]
Hi,

I greatly appreciate your input.

I do currently have `libjpeg-turobo` installed and I am using the max concurrency on my system.

I will test adjusting the quality of the resize.

Thank you,

Enrico

**Comment by blefaudeux** [comment]
big images should be great for datago, you should see very smooth CPU use all around. Could be tied to the resize quality then and these settings then, eventually datago should always be faster if apples to apples (just because there's very little python in the way, nothing wrong with torch per say)

![Screenshot 2024-11-12 at 6 17 10 PM](https://github.com/user-attachments/assets/8554f8fc-7a61-4d75-92c4-c1881b09ad23)

You can check this by not doing a crop & resize, in this case datago should be faster or there's something wrong

**Comment by blefaudeux** [comment]
>  I am using the max concurrency on my system

Sidenote in that you can visualize the system load live using, for instance, btop. Concurrency here can be well above the number of vCPUs, as you can also use it to mask some of the IO latency. This also goes for torch processes by the way, just saying that there are empirical optimums but hard to completely predict, you can play with that to check it out

**Comment by conceptofmind** [comment]
I am currently using above the number of vCPUs available on the system in concurrency.

I will test the other configuration settings.

Thank you.

**Comment by blefaudeux** [comment]
> Image Flattened
that means you have some 4-channels PNGs, in that case the code currently flattens them into 3 channels

**Comment by conceptofmind** [comment]
Thank you for the clarification. I am going to test on a much larger machine now as well.

**Comment by blefaudeux** [comment]
would you mind trying to build the package yourself ? Not sure why yet, but I've just seen that the package built by the CI and sent to pypi was a lot slower, it's not using all the CPU cores (possibly because it was built on a super small machine and some setting sticks). Locally it's night and day (settings may not be optimal for both, but that's like 5x faster than the pypi package)

![image](https://github.com/user-attachments/assets/6db87c5f-4c70-4e1e-b18b-92923bfd8ca1)
![image](https://github.com/user-attachments/assets/edcce80b-0843-46b2-acc6-3388124067d4)

**Comment by blefaudeux** [comment]
pypi package update, but still slow, using a single core, that's probably why you're seeing bad perf. GOMAXPROCS doesn't change a thing.. In the meantime you can build the package with the provided script and install it from there, you should see a much better perf

**Comment by conceptofmind** [comment]
Hi @blefaudeux ,

Thank you for the update.

I will build the package and report results.

Thank you,

Enrico

**Comment by conceptofmind** [comment]
Hi @blefaudeux,

Here are the new benchmark results following building the package.

```
Datago FPS 135.54
Stopping the datago client
Metadata fetch goroutine wrapping up
Image flattened
Image flattened
Image flattened
Image flattened
Datago client stopped
Benchmarking torch dataloader
Torch FPS 115.04
``` 

Thank you,

Enrico

**Comment by blefaudeux** [comment]
still the case after a couple of changes today, asked a few colleagues but everyone is perplex

<img width="812" alt="Screenshot 2024-11-14 at 11 17 05 PM" src="https://github.com/user-attachments/assets/d84389aa-9bb7-48c3-a671-029d6fe00fcc">
<img width="676" alt="Screenshot 2024-11-14 at 11 13 53 PM" src="https://github.com/user-attachments/assets/f38c4e91-9803-45e2-bb19-c87767397739">

**Comment by conceptofmind** [comment]
Hi @blefaudeux ,

I appreciate the update. 

Glad to know the results look correct from building the package from source.

**Comment by blefaudeux** [comment]
@conceptofmind could you report the go version you used locally (which worked in terms of perf) ? `go version`
CI is using 1.23 and I tested 1.18 locally, trying to explore this axis

**Comment by conceptofmind** [comment]
Hi @blefaudeux ,

The go version is `go version go1.18.1 linux/amd64`.

**Comment by blefaudeux** [comment]
waiting for your confirmation @conceptofmind, but I think the most recent pypi build (2024.11.9) is a fix :)

**Comment by conceptofmind** [comment]
I will test it out now.

Thank you!

**Comment by conceptofmind** [comment]
I am now receiving the error, `AttributeError: 'ImagePayload' object has no attribute 'DataPtr'`, after installing the package through pypi. I have not changed anything else in the benchmark script.

**Comment by blefaudeux** [comment]
ah, I've simplified this in recent PRs, you just need to update on the latest main (`git pull --rebase` if you're already on main). We had issues with memory leaks in some circumstances internally, and I think this could fix it

**Comment by conceptofmind** [comment]
Hi @blefaudeux ,

`git pull --rebase` did work.

Here are the results from installing the python package.

Test 1:
```
datago.SourceFileSystemConfig
Creating a FileSystem-backed dataloader
Supported image extensions [.jpg .jpeg .png .JPEG .JPG .PNG]
Rank and World Size 0 1
Cropping and resizing images
Base image size | downsampling ratio | min | max: 512 16 0.5 2
Datago FPS 117.90
Stopping the datago client
Image flattened
Image flattened
Image flattened
Datago client stopped
Benchmarking torch dataloader
Torch FPS 92.21
```
Test 2:
```
Datago FPS 108.73
Stopping the datago client
Image flattened
Image flattened
Image flattened
Datago client stopped
Benchmarking torch dataloader
Torch FPS 96.44
```
Thank you,

Enrico

**Comment by blefaudeux** [comment]
Thanks, looks good to me then ! The default settings in terms of concurrency & process numbers for torch (not the same, you can have a lot more concurrent workloads in datago than your number of CPUs, _these are not processes_) are a bit random, feel free to play around but the pypi package looks good to me.

Rule of thumb is that there will be a bigger difference in between datago and torch 
- if you don´t resize and use high res images (torch can suffer from IPC since there are multiple processes)
- if you resize to high definition images (same as above)
- if you use high quality resizing (more CPU work)

Else the filesystem use case is not why we built datago (focus was an optimized VectorDB client), it could probably improved over time

**Comment by conceptofmind** [comment]
Ok. Great. Thank you for the help. 

I will likely open up one more issue for when scaling this with ddp/fsdp.

**Comment by blefaudeux** [comment]
gone now with the rust release @conceptofmind, you can give it a new spin and should get some good speed no matter the platform

**Comment by conceptofmind** [comment]
> gone now with the rust release [@conceptofmind](https://github.com/conceptofmind), you can give it a new spin and should get some good speed no matter the platform

Awesome. Thank you!

I will give it a run later today.
